spring:
  application:
    name: auth-service

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces

secret:
  web-app: secret
  server-app: secret

jwt:
  secret: mySecretKey
